import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, writeFileSync, rmSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generate } from "../src/generate.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const jsonFixture = join(__dirname, "fixtures/petstore.json");
const yamlFixture = join(__dirname, "fixtures/petstore.yaml");
const outDir = join(__dirname, ".output");

function cleanup() {
  if (existsSync(outDir)) rmSync(outDir, { recursive: true });
}

describe("generate — JSON input", () => {
  before(cleanup);
  after(cleanup);

  it("generates all expected files", async () => {
    await generate({ input: jsonFixture, output: outDir });

    assert.ok(existsSync(join(outDir, "types/pets.types.ts")));
    assert.ok(existsSync(join(outDir, "controllers/pets.controller.interface.ts")));
    assert.ok(existsSync(join(outDir, "routes/pets.routes.ts")));
    assert.ok(existsSync(join(outDir, "types/store.types.ts")));
    assert.ok(existsSync(join(outDir, "controllers/store.controller.interface.ts")));
    assert.ok(existsSync(join(outDir, "routes/store.routes.ts")));
  });

  it("generated files contain AUTO-GENERATED header", async () => {
    const content = readFileSync(join(outDir, "types/pets.types.ts"), "utf-8");
    assert.ok(content.includes("AUTO-GENERATED by openapi-to-express"));
  });
});

describe("generate — YAML input", () => {
  before(cleanup);
  after(cleanup);

  it("generates files from YAML spec", async () => {
    await generate({ input: yamlFixture, output: outDir });

    assert.ok(existsSync(join(outDir, "types/pets.types.ts")));
    assert.ok(existsSync(join(outDir, "controllers/pets.controller.interface.ts")));
    assert.ok(existsSync(join(outDir, "routes/pets.routes.ts")));
  });

  it("generated types are correct", async () => {
    const content = readFileSync(join(outDir, "types/pets.types.ts"), "utf-8");
    assert.ok(content.includes("export interface Pet {"));
    assert.ok(content.includes("export interface PetListResponse {"));
    assert.ok(content.includes("pets: Pet[];"));
  });
});

describe("generate — custom directories", () => {
  before(cleanup);
  after(cleanup);

  it("generates files in custom directories", async () => {
    await generate({
      input: jsonFixture,
      output: outDir,
      dirs: { types: "models", controllers: "interfaces", routes: "api" },
    });

    assert.ok(existsSync(join(outDir, "models/pets.types.ts")));
    assert.ok(existsSync(join(outDir, "interfaces/pets.controller.interface.ts")));
    assert.ok(existsSync(join(outDir, "api/pets.routes.ts")));
  });

  it("import paths use custom directory names", async () => {
    const routes = readFileSync(join(outDir, "api/pets.routes.ts"), "utf-8");
    assert.ok(routes.includes("../interfaces/pets.controller.interface"));
  });
});

describe("generate — error handling", () => {
  it("throws on non-existent file", async () => {
    await assert.rejects(
      () => generate({ input: "nonexistent.json", output: outDir }),
      { message: /Cannot resolve input/ },
    );
  });
});

describe("generate — overwrite protection", () => {
  before(cleanup);
  after(cleanup);

  it("skips files that were manually modified", async () => {
    // First generate
    await generate({ input: jsonFixture, output: outDir });
    assert.ok(existsSync(join(outDir, "types/pets.types.ts")));

    // Manually modify one file (remove the auto-generated marker)
    writeFileSync(join(outDir, "types/pets.types.ts"), "// Custom code\nexport interface Pet {}\n");

    // Regenerate
    await generate({ input: jsonFixture, output: outDir });

    // The manually modified file should be untouched
    const content = readFileSync(join(outDir, "types/pets.types.ts"), "utf-8");
    assert.ok(content.includes("// Custom code"));
    assert.ok(!content.includes("AUTO-GENERATED"));
  });

  it("overwrites files that still have the auto-generated marker", async () => {
    // store.types.ts was not modified — should be overwritten
    const content = readFileSync(join(outDir, "types/store.types.ts"), "utf-8");
    assert.ok(content.includes("AUTO-GENERATED"));
  });
});
