/**
 * Main generation orchestrator.
 *
 * Reads an OpenAPI spec, classifies schemas, and writes all generated files
 * into the target directory with configurable folder names.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, resolve, extname } from "node:path";
import YAML from "yaml";
import { parseSpec, classifySchemas } from "./parser/spec-parser.js";
import { generateTypesFile } from "./generators/types-generator.js";
import { generateControllerInterface } from "./generators/controller-generator.js";
import { generateExpressRoutes } from "./generators/routes-express-generator.js";

const HEADER = `// ============================================================================
// AUTO-GENERATED by openapi-to-express — do not edit manually.
// Regenerate with: npm run generate
// ============================================================================

`;

export interface DirectoryConfig {
  /** Folder name for generated types (default: "types") */
  types: string;
  /** Folder name for generated controller interfaces (default: "controllers") */
  controllers: string;
  /** Folder name for generated routes (default: "routes") */
  routes: string;
}

export interface GenerateOptions {
  /** OpenAPI specification — can be a file path, URL, or JSON string content */
  input: string;
  /** Output directory (e.g. "src") */
  output: string;
  /** Custom folder names for generated output */
  dirs?: Partial<DirectoryConfig>;
  /** If true, only print what would be generated without writing files */
  dryRun?: boolean;
}

const DEFAULT_DIRS: DirectoryConfig = {
  types: "types",
  controllers: "controllers",
  routes: "routes",
};

function parseSpecContent(raw: string, hint?: string): any {
  const trimmed = raw.trimStart();

  // Try JSON first if it looks like JSON or hint says so
  if (trimmed.startsWith("{") || hint === ".json") {
    try {
      return JSON.parse(raw);
    } catch {
      // Fall through to YAML
    }
  }

  // Try YAML (also handles JSON since JSON is valid YAML)
  try {
    return YAML.parse(raw);
  } catch {
    throw new Error("Failed to parse input as JSON or YAML.");
  }
}

export async function resolveInput(input: string): Promise<any> {
  // URL
  if (input.startsWith("http://") || input.startsWith("https://")) {
    const res = await fetch(input);
    if (!res.ok) throw new Error(`Failed to fetch spec from ${input}: ${res.status} ${res.statusText}`);
    const raw = await res.text();
    return parseSpecContent(raw, extname(new URL(input).pathname));
  }

  // File path
  const filePath = resolve(input);
  if (existsSync(filePath)) {
    const raw = readFileSync(filePath, "utf-8");
    return parseSpecContent(raw, extname(filePath));
  }

  // String content (JSON or YAML)
  const trimmed = input.trimStart();
  if (trimmed.startsWith("{") || trimmed.startsWith("openapi")) {
    return parseSpecContent(input);
  }

  throw new Error(`Cannot resolve input: "${input}" is not a valid file path, URL, or JSON/YAML string.`);
}

export async function generate(options: GenerateOptions): Promise<void> {
  const outDir = resolve(options.output);
  const dirs: DirectoryConfig = { ...DEFAULT_DIRS, ...options.dirs };

  const dryRun = options.dryRun ?? false;
  const spec = await resolveInput(options.input);
  const parsed = parseSpec(spec);
  const { common, perTag } = classifySchemas(parsed.byTag, parsed.schemas);
  const commonSet = new Set(common);

  if (!dryRun) {
    mkdirSync(join(outDir, dirs.types), { recursive: true });
    mkdirSync(join(outDir, dirs.controllers), { recursive: true });
    mkdirSync(join(outDir, dirs.routes), { recursive: true });
  }

  const AUTO_GENERATED_MARKER = "AUTO-GENERATED by openapi-to-express";
  let totalFiles = 0;
  let skippedFiles = 0;
  const filesPerDir = new Map<string, string[]>();

  function write(dir: string, name: string, content: string) {
    const filePath = join(outDir, dir, name);

    // Overwrite protection: skip files that exist but don't have our marker
    if (!dryRun && existsSync(filePath)) {
      const existing = readFileSync(filePath, "utf-8");
      if (!existing.includes(AUTO_GENERATED_MARKER)) {
        console.log(`  ${dir}/${name} (skipped — manually modified)`);
        skippedFiles++;
        return;
      }
    }

    if (!dryRun) {
      writeFileSync(filePath, HEADER + content, "utf-8");
    }
    const list = filesPerDir.get(dir) ?? [];
    list.push(name);
    filesPerDir.set(dir, list);
    console.log(`  ${dir}/${name}`);
    totalFiles++;
  }

  // 1. Common types (only if shared schemas exist)
  if (common.length > 0) {
    const { content } = generateTypesFile(common, parsed.schemas, new Set());
    write(dirs.types, "common.types.ts", content);
  }

  // 2. Per-tag files
  for (const [tag, operations] of parsed.byTag) {
    const tagLower = tag.toLowerCase();
    const tagSchemas = (perTag.get(tag) ?? []).sort();

    // Types
    const { content, imports } = generateTypesFile(tagSchemas, parsed.schemas, commonSet);
    let typesContent = "";
    if (imports.length > 0) {
      typesContent += `import type { ${imports.join(", ")} } from "./common.types";\n\n`;
    }
    typesContent += content;
    // Ensure file is a valid module even if no schemas were generated
    if (!typesContent.trim()) {
      typesContent = "export {};\n";
    }
    write(dirs.types, `${tagLower}.types.ts`, typesContent);

    // Controller interface
    write(
      dirs.controllers,
      `${tagLower}.controller.interface.ts`,
      generateControllerInterface(tag, operations),
    );

    // Routes
    write(dirs.routes, `${tagLower}.routes.ts`, generateExpressRoutes(tag, operations, dirs));
  }

  // 3. Barrel (index.ts) files per directory
  for (const [dir, files] of filesPerDir) {
    const exports = files
      .map((f) => `export * from "./${f.replace(/\.ts$/, "")}";`)
      .join("\n");
    write(dir, "index.ts", exports + "\n");
  }

  const prefix = dryRun ? "Would generate" : "Generated";
  let summary =
    `\n${prefix} ${totalFiles} files from ${parsed.byTag.size} tag(s)` +
    (common.length > 0 ? ` (${common.length} shared types in common.types.ts)` : "");
  if (skippedFiles > 0) {
    summary += ` — ${skippedFiles} file(s) skipped (manually modified)`;
  }
  console.log(summary + ".");
}
